version: '3.8'

services:
  # PHP-FPM Service for Laravel 11
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_pw_api_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel11_api
    depends_on:
      - db
      - redis

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: laravel11_api_webserver
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel11_api
    depends_on:
      - app

  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: laravel11_api_db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel_pw_api_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: laravel11_user
      MYSQL_PASSWORD: laravel11_password
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel11_api

  # Redis Service
  redis:
    image: redis:7-alpine
    container_name: laravel11_api_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - laravel11_api

  # Composer Service
  composer:
    image: composer:latest
    container_name: laravel11_api_composer
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - laravel11_api
    profiles:
      - composer

  # Artisan Service
  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_pw_api_artisan
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel11_api
    profiles:
      - artisan

# Docker Networks
networks:
  laravel11_api:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
